<?php
/**
 * @file
 * mediacommons_homepage_umbrella.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function mediacommons_homepage_umbrella_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'field_bundle_settings_node__front_page_post';
  $strongarm->value = array(
    'view_modes' => array(
      'full' => array(
        'custom_settings' => TRUE,
      ),
      'teaser' => array(
        'custom_settings' => TRUE,
      ),
      'rss' => array(
        'custom_settings' => FALSE,
      ),
      'search_index' => array(
        'custom_settings' => FALSE,
      ),
      'search_result' => array(
        'custom_settings' => FALSE,
      ),
      'print' => array(
        'custom_settings' => FALSE,
      ),
      'diff_standard' => array(
        'custom_settings' => FALSE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
      'hub_home_vertical' => array(
        'custom_settings' => FALSE,
      ),
      'hub_teaser_for_archive_page' => array(
        'custom_settings' => FALSE,
      ),
      'front_page_post_super_featured' => array(
        'custom_settings' => FALSE,
      ),
      'hub_teaser_compact' => array(
        'custom_settings' => FALSE,
      ),
      'revision' => array(
        'custom_settings' => FALSE,
      ),
    ),
    'extra_fields' => array(
      'form' => array(),
      'display' => array(),
    ),
  );
  $export['field_bundle_settings_node__front_page_post'] = $strongarm;

  return $export;
}
