<?php

/**
 * Implements hook_views_api().
 */
function mediacommons_views_views_api () {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implements hook_views_default_views().
 */
function mediacommons_views_views_default_views () {
  $views = array();
  $files = file_scan_directory(drupal_get_path('module', 'mediacommons_views') . '/views', '/\.inc/');
  foreach ($files as $absolute => $file) {
    require $absolute;
    if (isset($view)) {
      $views[$file->name] = $view;
      unset($view);
    }
  }
  return $views;
}
