<?php

function _mediacommons_globalnav_config() {
  
  if (function_exists('__host_sites')) {

  $sites = __host_sites();
  
  $site_name = '';
  
  $menu_name = 'menu-mcglobalnav';

  $leafs_increment = 0;
  
  $leaf_myaccount_increment = 0;
  
  $leaf_frontpage_increment = 0;  
  
  $menus = array(
    array(
      'menu_name' => $menu_name,
      'title' => 'MediaCommons Global Navigation',
      'description' => 'Global nav - Menu for navigating among projects ',
    ),
  );
  
  $leafs = array(
    array(
      'link_path' => $sites['mediacommons'],
      'link_title' => 'Front page',
      'menu_name' => $menu_name,
      'expanded' => 1,
      'external' => 1,
      'weight' => ++$leafs_increment,
      'customized' => 1,   
      'module' => 'menu',   
    ),
    array(
      'link_path' => 'user',
      'router_path' => 'user',
      'link_title' => 'My Account',
      'menu_name' => $menu_name,
      'expanded' => 1,
      'external' => 0,
      'weight' => ++$leafs_increment,
      'customized' => 1,    
      'module' => 'menu',        
    ),
    array(
      'link_path' => 'user/register',
      'router_path' => 'user/register',      
      'link_title' => 'Register',
      'menu_name' => $menu_name,
      'expanded' => 1,
      'external' => 0,
      'weight' => ++$leafs_increment,
      'customized' => 1,      
      'module' => 'menu',      
    ),
    array(
      'link_path' => 'user/login',
      'router_path' => 'user/login',      
      'link_title' => 'Log in',
      'menu_name' => $menu_name,
      'expanded' => 1,
      'external' => 0,
      'weight' => ++$leafs_increment,
      'customized' => 1,      
      'module' => 'menu',      
    ),        
  );  
  
  $links = array(
  
    'My Account' => array(

      // https://jira.nyu.edu/jira/browse/MC-327
      
      // My Profile
      array(
        'link_path' => 'user',
        'link_title' => 'My Profile',
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_myaccount_increment,
        'customized' => 0,      
        'module' => 'menu',        
      ),
      
      // My [channel] Dashboard       

      array(
        'link_path' => 'dashboard',
        'router_path' => 'dashboard',     
        'link_title' => "My $site_name Dashboard",
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_myaccount_increment,
        'customized' => 1,      
        'module' => 'menu',        
      ),
      
      // Log out
      array(
        'link_path' => 'user/logout',
        'link_title' => 'Log out',
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_myaccount_increment,
        'customized' => 0,      
        'module' => 'menu',        
      ),
      

    ),
  
    'Front page' =>  array(
    
     // Front Page Link for Mobile devices
      array(
        'link_path' => $sites['mediacommons'],
        'link_title' => 'MediaCommons Front Page',
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_frontpage_increment,
        'customized' => 1,      
        'module' => 'menu',        
      ),
      // Field Guide
      array(
        'link_path' => $sites['fieldguide'],
        'link_title' => 'Field Guide',
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_frontpage_increment,
        'customized' => 1,      
        'module' => 'menu',        
      ),
    
      // #Alt-Academy
      array(
        'link_path' => $sites['alt-ac'],
        'link_title' => '#Alt-Academy',
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_frontpage_increment,
        'customized' => 1,      
        'module' => 'menu',        
      ),
      
      // In Media Res
      array(
        'link_path' => $sites['imr'],
        'link_title' => 'In Media Res',
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_frontpage_increment,
        'customized' => 1,      
        'module' => 'menu',        
      ),

      // [in]Transition
      array(
        'link_path' => $sites['intransition'],
        'link_title' => '[in]Transition',      
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_frontpage_increment,
        'customized' => 1,      
        'module' => 'menu',        
      ),
      
      // MediaCommons Press
      array(
        'link_path' => 'http://mcpress.media-commons.org/',
        'link_title' => 'MediaCommons Press',
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_frontpage_increment,
        'customized' => 1,      
        'module' => 'menu',        
      ),
      
      // The New Everyday
      array(
        'link_path' => $sites['tne'],
        'link_title' => 'The New Everyday',
        'menu_name' => $menu_name,
        'expanded' => 0,
        'external' => 1,
        'weight' => ++$leaf_frontpage_increment,
        'customized' => 1,      
        'module' => 'menu',        
      ),                  
      
    ),
      
  );

  
  // Save menu group into menu_custom table
  foreach ( $menus as $menu ) {
    // Look the table first if the data does exist
    $exists = db_query("SELECT * FROM {menu_custom} WHERE menu_name=:menu_name", array(':menu_name' => $menu['menu_name']))->fetchField();
    // Save the record if the data does not exist
    if ($exists)  {
      menu_delete($menu);
    }
    menu_save($menu);
  }

  foreach ( $leafs as $link ) {

    // Look the table first if the data does exist
    $exists = db_query("SELECT menu_name from {menu_links} WHERE link_title=:link_title AND link_path=:link_path", array(':link_title' =>  $link['link_title'], ':link_path' => $link['link_path']))->fetchField();
    
    // Save the record if the data does not exist
    if ( ! $exists || ( $exists && $exists !== $menu_name ) ) menu_link_save( $link );
    
  }  

  foreach ( $links as $leaf => $leaf_links ) {
    // Look for the parent is available
    $parent_leaf_mlid = db_query("SELECT mlid from {menu_links} WHERE link_title=:link_title AND menu_name=:menu_name", array(':link_title' =>  $leaf , ':menu_name' => $menu_name ))->fetchField();
    if ( $parent_leaf_mlid ) {
      foreach ( $leaf_links as $link ) {
        // Look the table first if the data does exist
        $exists = db_query("SELECT menu_name from {menu_links} WHERE link_title=:link_title AND link_path=:link_path", array(':link_title' =>  $link['link_title'], ':link_path' => $link['link_path']))->fetchField();
        if ( ! $exists || ( $exists && $exists !== $menu_name ) ) {
          // Save the record if the data does not exist
          $link['plid'] = $parent_leaf_mlid;
          menu_link_save($link);
        }
      }
    }
  }

  // Translatables
  // Included for use with string extractors like potx.
  
  t('Global nav - Menu for navigating among projects ');
  t('MediaCommons Global Navigation');
  t('#Alt-Academy');
  t('Front page');
  t('In Media Res');
  t('Log in');
  t('Log out');
  t('MediaCommons Press');
  t('My Account');
  t('The New Everyday');
  t('[in]Transition');

    //array(
    //  'module' => 'menu',
    //  'delta' => 'menu-mcglobalnav',
    //  'theme' => $default_theme,
    //  'status' => 1,
    //  'weight' => 0,
    //  'region' => 'globalnav',
    //  'pages' => '',
    //  'cache' => -1,
    //  'visibility' => 0,
    //),  

  $menu_block = array(
    'module' => 'menu',
    'delta' => $menu_name,
    'theme' => 'mediacommons', // Either get the active theme or you can do it for all themes
    'region' => 'globalnav', // Where you want to place it, theme dependant
    'status' => 1,
    'pages' => '',
  );

  db_delete('block')
    ->condition('module', 'menu')
    ->condition('delta', $menu_name)
    ->execute();  

  drupal_write_record('block', $menu_block);    

  menu_cache_clear_all();

  $hostname = gethostname();

  variable_set('mediacommons_hostname', $hostname);

  }

}

// https://www.webomelette.com/drupal-modules-debug-emails
function mediacommons_globalnav_cron() {
  $hostname = gethostname();
  $mediacommons_hostname = variable_get('mediacommons_hostname');
  if ($mediacommons_hostname != $hostname) {
    _mediacommons_globalnav_config();
  }
}
