<?php

function mediacommons_managment_init() {
}

function mediacommons_managment_findById($identifier) {
  $query = 'SELECT entity_id AS nid FROM {field_data_field_identifier} WHERE field_identifier_value = :identifier';
  $result = db_query($query, array(':identifier' => $identifier));
  $record = $result->fetchObject();
  if ($record) {
    return $record->nid;
  } else {
    return false;
  }
}

function mediacommons_managment_projects() {
  $projects = &drupal_static(__FUNCTION__, array());
  if (empty($projects)) {
    $nodes = node_load_multiple(array(), array('type' => 'project'));
    foreach ($nodes as $project) {
      $wrapper = entity_metadata_wrapper('node', $project);
      $identifier = $wrapper->field_identifier->value();
      $projects[$identifier] = array(
        'uuid' => $project->uuid,
        'label' => $project->title,
        'identifier' => $identifier,
        'path' => $wrapper->field_path->value(),
        'shortname' => $wrapper->field_shortname->value(),
      );
    }
  }
  return $projects;
}

function mediacommons_managment_default_content() {
  return json_decode(file_get_contents(dirname(__DIR__) . '/features/projects/nodes.json'));
}

function mediacommons_managment_import_default_projects () {

  drupal_flush_all_caches();

  $data = mediacommons_managment_default_content();

  $values = array(
    'type' => 'project',
    'uid' => 1,
    'status' => 1,
    'comment' => 0,
    'promote' => 0,
    'language' => LANGUAGE_NONE,
  );

  foreach ($data->nodes as $node) {
    if (!mediacommons_managment_findById($node->identifier)) {
      $entity = entity_create('node', $values);
      $wrapper = entity_metadata_wrapper('node', $entity);
      $wrapper->title->set($node->label);
      $wrapper->field_identifier->set($node->identifier);
      $wrapper->field_shortname->set($node->shortname);
      $wrapper->field_description->set($node->description);
      $wrapper->field_path->set($node->path);
      $wrapper->save();
      unset($wrapper);
      unset($entity);
    }
  }

}
