<?php

function mediacommons_utilities_get_root_url() {
  static $root_url;

  if ( $root_url ) {
    return $root_url;
  }

  // NOTE: gethostname() does not work for local /etc/hosts/ aliases.
  $hostname = $_SERVER['SERVER_NAME'];

  // Don't just do `$_SERVER['HTTPS'] ? 'https' : 'http';`.  This will throw an
  // error "Notice: Undefined index: HTTPS" which is not fatal but is printed on
  // on the page.
  if ( array_key_exists( 'HTTPS', $_SERVER ) ) {
    // It's unclear from http://php.net/manual/en/reserved.variables.server.php
    // whether the existence of the key is enough.  Test if it's "non-empty".
    $protocol = empty( $_SERVER['HTTPS'] ) ? 'https' : 'http';
  } else {
    $protocol = 'http';
  }

  $port = $_SERVER['SERVER_PORT'] === '80' ? '' : ':' . $_SERVER['SERVER_PORT'];

  $root_url = "${protocol}://${hostname}${port}";

  return $root_url;
}

function mediacommons_homepage_umbrella_url() {
  return mediacommons_utilities_get_root_url() . '/mediacommons';
}

function mediacommons_utilities_project_url($project) {
  return mediacommons_utilities_get_root_url() . '/' . $project;
}

function mediacommons_utilities_is_project_redirect($path) {
  // Some browsers treat \ as / so normalize to forward slashes.
  $path = str_replace('\\', '/', $path);
  // If the path starts with a backslash then it is considered an project redirect
  $substr = substr($path, 0, 1);

  if ($substr == '/') return drupal_strip_dangerous_protocols($path);

  else return FALSE;

}
