<?php
/**
 * @file
 * mediacommons_image_styles_and_date_formats.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function mediacommons_image_styles_and_date_formats_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'imagefield_crop_info';
  $strongarm->value = array();
  $export['imagefield_crop_info'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'user_pictures';
  $strongarm->value = '1';
  $export['user_pictures'] = $strongarm;

  return $export;
}
