<?php

/**
 * @file
 * Module file for mediacommons_twitter.
 */

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function mediacommons_twitter_block_info () {
  $blocks['mediacommons_twitter'] = array(
    'info' => t('MediaCommons: Twitter block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function mediacommons_twitter_block_configure ($delta = '') {
  $form = array();
  if ($delta == 'mediacommons_twitter') {
    $form['mediacommons_twitter_label'] = array(
      '#type' => 'textfield',
      '#title' => t('MediaCommons: Link label'),
      '#size' => 60,
      '#description' => t('Link label'),
      '#default_value' => variable_get('mediacommons_twitter_label', ''),
    );
    $form['mediacommons_twitter_user'] = array(
      '#type' => 'textfield',
      '#title' => t('MediaCommons: Twitter user'),
      '#size' => 60,
      '#description' => t('Twitter username'),
      '#default_value' => variable_get('mediacommons_twitter_user', ''),
    );
    $form['mediacommons_twitter_url'] = array(
      '#type' => 'textfield',
      '#title' => t('MediaCommons: Twitter URL'),
      '#size' => 60,
      '#description' => t('Use this if you would like to use a Twitter URL instead of the Twitter username. Twitter user should be left empty if you plan to provide a URL.'),
      '#default_value' => variable_get('mediacommons_twitter_url', ''),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function mediacommons_twitter_block_save($delta = '', $edit = array()) {
  if ($delta == 'mediacommons_twitter') {
    variable_set('mediacommons_twitter_user', $edit['mediacommons_twitter_user']);
    variable_set('mediacommons_twitter_label', $edit['mediacommons_twitter_label']);
    variable_set('mediacommons_twitter_url', $edit['mediacommons_twitter_url']);    
  }
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function mediacommons_twitter_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'mediacommons_twitter':
      $block['subject'] = t('MediaCommons: Twitter block');
      $block['content'] = mediacommons_twitter_content();
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function mediacommons_twitter_content() {
  // https://dev.twitter.com/web/embedded-timelines/parameters
  $output = '';
  $attibutes_string = '';
  $label = variable_get('mediacommons_twitter_label', '&nbsp;');
  $username = variable_get('mediacommons_twitter_user', null);
  $content_url = variable_get('mediacommons_twitter_url', null);
  $pattern = '/https:\/\/twitter.com/';
  $script = '<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>';
  $attibutes = array(
    'data-height' => '600',
    'data-theme' => 'dark',
  );
  if (!is_null($username)) {
    $attibutes['href'] = 'https://twitter.com/' . $username;
  }
  elseif (!is_null($content_url) && preg_match($pattern, $content_url)) {
    $attibutes['href'] = $content_url;
  }
  foreach ($attibutes as $key => $attibute) {
    $attibutes_string .= ' ' . $key . '="' . $attibute . '"';
  }
  $output = '<a class="twitter-timeline mediacommons_twitter"' . $attibutes_string . '>' . $label . '</a>' . $script;
  return array('#markup' => $output);
}
