<?php

/**
 * @file
 * Module file for mediacommons_block.
 */

//function mediacommons_blocks_init () {}

/**
 * Implements hook_menu().
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu/7.x
 *
 * Define menu items and page callbacks.
 */
function mediacommons_blocks_menu () {

  $items = array();

  // @TODO: Not working
  $items['admin/structure/mcblock'] = array(
    'title' => 'Add block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('block_add_block_form'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mediacommons_blocks.admin.inc',
  );

  $items['admin/structure/mcblock/add'] = array(
    'title' => 'MediaCommons: Add block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mediacommons_blocks_add_block'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;

}

function mediacommons_blocks_add_block ($form, &$form_state) {

  module_load_include('inc', 'block', 'block.admin');

  $form = block_admin_configure($form, $form_state, 'mediacommons_blocks', NULL);

  $types = mediacommons_blocks_list_types();

  $types_options = array();

  foreach ($types as $type => $key) {
    $types_options[$key] = $type;
  }

  $default_value = 0;

  $label = '';

  $form['settings']['mediacommons_blocks_label'] = array(
    '#type' => 'textfield',
    '#title' => t('Block label'),
    '#size' => 60,
    '#description' => t('Label'),
    '#default_value' => $label,
  );

  $form['settings']['mediacommons_blocks_type'] = array(
    '#type' => 'select',
    '#title' => t('Type of source'),
    '#default_value' => $default_value,
    '#options' => $types_options,
    '#description' => t('At the moment we do not allow to change the type of the source.'),
  );

  $form['#validate'][] = 'mediacommons_blocks_add_block_validate';

  $form['#submit'][] = 'mediacommons_blocks_add_block_submit';

  return $form;

}

/**
 * https://api.drupal.org/api/drupal/modules%21block%21block.admin.inc/function/block_add_block_form_validate/7.x
 */
function mediacommons_blocks_add_block_validate ($form, &$form_state) {
  return TRUE;
}

/**
 * https://api.drupal.org/api/drupal/modules%21block%21block.admin.inc/function/block_add_block_form_submit/7.x
 */
function mediacommons_blocks_add_block_submit ($form, &$form_state) {
  
  $label = (isset($form['settings']['mediacommons_blocks_label']['#value']) ? $form['settings']['mediacommons_blocks_label']['#value'] : '');
  
  $type = $form['settings']['mediacommons_blocks_type']['#value'];  

  // for types see mediacommons_blocks_list_types()
  switch ($type) {
    case 0 : // plaintext
      $options = array(
        'type' => 'plaintext',
        'label' => $label,
      );
      break;
    case 1 : // fulltext
      $options = array(
        'type' => 'fulltext',
        'label' => $label,
      );
      break;
    case 2 : // source
      $options = array(
        'type' => 'source',
        'label' => $label,
      );
      break;
    case 3 : // callback
      $options = array(
        'type' => 'callback',
        'label' => $label,
      );
      break;
  }

  $options['new'] = TRUE;

  $block = mediacommons_blocks_save_block($options);

  cache_clear_all();

  $form_state['redirect'] = format_string('admin/structure/block/manage/mediacommons_blocks/@mbid/configure', array('@mbid' => $block->mbid));

}

/**
 * Implements hook_block_info().
 * https://api.drupal.org/api/drupal/modules%21block%21block.api.php/function/hook_block_info/7.x
 *
 * This hook declares what blocks are provided by the module.
 */
function mediacommons_blocks_block_info () {
  $blocks = array();
  foreach (mediacommons_blocks_blocks() as $block) {
    $label = unserialize($block->label);
    $configuration = unserialize($block->options);
    if (empty($label)) {
      $label = 'Untitled';
    }
    $configuration['info'] = format_string('Mediacommons Blocks: @label', array('@label' => $label));
    $blocks[$block->mbid] = $configuration;
  }
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function mediacommons_blocks_block_view ($delta = '') {
  $block = array();
  $content = '';
  // The $delta parameter tells us which block is being requested.
  if ($delta && preg_match('/^mc_/', $delta)) {
    $data = mediacommons_blocks_block_load($delta);
    if ($data) {
      $subject = unserialize($data->label);
      // for types see mediacommons_blocks_list_types()
      switch ($data->type) {
        case 0 : // plaintext
        case 1 : // fulltext
        case 2 : // source        
          $content = unserialize($data->content);
          break;
        case 3 : // callback
          $callback = unserialize($data->callback);
          if (function_exists($callback)) {
            $content = $callback();
          }
          break;
      }
      $block['subject'] = $subject;
      $block['content'] = array('#markup' => $content);

    }
  }
  return $block;
}

/**
 * Implements hook_block_configure().
 * https://api.drupal.org/api/drupal/modules%21block%21block.api.php/function/hook_block_configure/7.x
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function mediacommons_blocks_block_configure ($delta = '') {
  
  $form = array();

  if ($delta && preg_match('/^mc_/', $delta)) {

    $block = mediacommons_blocks_block_load($delta);

    $label = unserialize($block->label);

    $types = mediacommons_blocks_list_types();

    $types_options = array();
    
    foreach ($types as $type => $key) {
      $types_options[$key] = $type;
    }

    $block_type = $types_options[$block->type];

    $default_value = isset($block->type) ? $block->type : 0;

    $form['mediacommons_blocks_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Block label'),
      '#size' => 60,
      '#description' => t('Label'),
      '#default_value' => $label,
    );

    $form['mediacommons_blocks_type'] = array(
      '#type' => 'select',
      '#title' => t('Type of source'),
      '#default_value' => $default_value,
      '#options' => $types_options,
      '#description' => t('At the moment we do not allow to change the type of the source.'),
      '#disabled' => TRUE,
    );

    // we must set type before we allow to configure the block
    if (isset($block->type)) {
      switch ($block_type) {
        case 'source' :
          $url = $block->url;
          $form['mediacommons_blocks_url'] = array(
            '#title' => t('Source URL'),
            '#type' => 'textfield',
            '#description' => t('The URL of the datasource you want to use'),
            '#default_value' => $url,      
          );
          break;
        case 'callback' :
          $callback = unserialize($block->callback);
          $form['mediacommons_blocks_callback'] = array(
            '#title' => t('Function callback'),
            '#type' => 'textfield',
            '#description' => t('The name of the function to call. The function must exist.'),
            '#default_value' => $callback,      
          );
          break;
        case 'fulltext' :
          $content = unserialize($block->content);
          $form['mediacommons_blocks_content'] = array(
            '#title' => t('Content'),
            '#type' => 'textarea',
            '#description' => t('Full HTML'),
            '#default_value' => $content,      
          );
          break;
        case 'plaintext' :
          $content = unserialize($block->content);
          $form['mediacommons_blocks_plaintext'] = array(
            '#title' => t('Content'),
            '#type' => 'textarea',
            '#description' => t('Plain text'),
            '#default_value' => $content,
          );
          break;
      }
    }
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function mediacommons_blocks_block_save ($delta = '', $edit = array()) {
  if ($delta && preg_match('/^mc_/', $delta)) {
    $block = mediacommons_blocks_block_load($delta);
    $types = mediacommons_blocks_list_types();
    $types_options = array();
    foreach ($types as $type => $key) {
      $types_options[$key] = $type;
    }
    $type = $types_options[$edit['mediacommons_blocks_type']];
    $label = $edit['mediacommons_blocks_label'];
    switch ($type) {
      case 'source' :
        $options = array(
          'url' => $edit['mediacommons_blocks_url'],
          'mbid' => $delta,
        );      
        return _mediacommons_blocks_save_source($type, $label, $delta, $options);
      case 'callback' :
        $options = array(
          'url' => $edit['mediacommons_blocks_callback'],
          'mbid' => $delta,
        );
        return _mediacommons_blocks_save_callback($type, $label, $delta, $options);
      case 'fulltext' :
        $options = array(
          'content' => $edit['mediacommons_blocks_content'],
          'mbid' => $delta,
        );
        return _mediacommons_blocks_save_fulltext($type, $label, $delta, $options);
      case 'plaintext' :
        $options = array(
          'content' => $edit['mediacommons_blocks_plaintext'],
          'mbid' => $delta,
        );
        return _mediacommons_blocks_save_plaintext($type, $label, $delta, $options);
    }
  }
}

function _mediacommons_blocks_save_fulltext($type, $label, $mbid, $options) {
  
  $content = (isset($options['content'])) ? $options['content'] : '';

  $configuration = (isset($options['options'])) ? $options['options'] : array();

  $block = mediacommons_blocks_block_load($mbid);

  if (!$block) {
    db_insert('mediacommons_blocks_blocks')
      ->fields(array(
        'mbid' => $mbid,
        'type' => mediacommons_blocks_list_types($type),
        'label' => serialize($label),
        'content' => serialize($content),
        'created' => time(),
        'proceed' => time(),
        'options' => serialize($configuration),
        'expire' => 0, // we don't expire fulltext
      ))
      ->execute();
  }
  else {
    db_update('mediacommons_blocks_blocks')
      ->fields(array(
        'content' => serialize($content),
        'label' => serialize($label),                  
        'proceed' => REQUEST_TIME,
       ))
      ->condition('mbid', $options['mbid'], '=')
      ->execute();
  }

  // create a wathchdog record
  return mediacommons_blocks_block_load($mbid);

}

function _mediacommons_blocks_save_plaintext ($type, $label, $mbid, $options) {
  $content = (isset($options['content'])) ? $options['content'] : '';
  $text = $content;
  $block = mediacommons_blocks_block_load($mbid);
  if (!$block) {
    db_insert('mediacommons_blocks_blocks')
      ->fields(array(
        'mbid' => $mbid,
        'type' => mediacommons_blocks_list_types($type),
        'label' => serialize($label),
        'content' => serialize($text),
        'created' => time(),
        'proceed' => time(),
        'expire' => 0, // we don't expire plaintext
      ))
      ->execute();
  }
  else {
    db_update('mediacommons_blocks_blocks')
      ->fields(array(
        'content' => serialize($text),
        'label' => serialize($label),                  
        'proceed' => REQUEST_TIME,
      ))
      ->condition('mbid', $options['mbid'], '=')
      ->execute();
  }
  // create a wathchdog record
  return mediacommons_blocks_block_load($mbid);
}

function _mediacommons_blocks_save_callback ($type, $label, $mbid, $options) {
  $callback = (isset($options['callback'])) ? $options['callback'] : '';
  $block = mediacommons_blocks_block_load($mbid);
   if (!$block) {
     db_insert('mediacommons_blocks_blocks')
       ->fields(array(
         'mbid' => $mbid,
         'type' => mediacommons_blocks_list_types($type),
         'label' => serialize($label),
         'callback' => serialize($callback),
         'created' => time(),
         'proceed' => time(),
         'expire' => 0, // maybe later on
       ))
       ->execute();
   }
   else {
     db_update('mediacommons_blocks_blocks')
       ->fields(array(
         'callback' => serialize($callback),
         'label' => serialize($label),                  
         'proceed' => REQUEST_TIME,
       ))
       ->condition('mbid', $options['mbid'], '=')
       ->execute();
  }
  // create a wathchdog record
  return mediacommons_blocks_block_load($mbid);
}

function _mediacommons_blocks_save_source ($type, $label, $mbid, $options) {
  $url = (isset($options['url'])) ? check_url($options['url']) : NULL;
  $block = mediacommons_blocks_block_load($mbid);
  $text = '';
  if ($url) {
    $request = drupal_http_request($url);
    if (isset($request->status_message)) {
      $status_message = strtolower(check_plain($request->status_message));
      if ($status_message == 'ok') {
        $text = $request->data;
      }
    }
  }
  if (!$block) {
    db_insert('mediacommons_blocks_blocks')
      ->fields(array(
        'mbid' => $mbid,
        'type' => mediacommons_blocks_list_types($type),
        'label' => serialize($label),
        'url' => $url,
        'content' => serialize($text),
        'created' => time(),
        'proceed' => time(),
        'expire' => time() + (3600 * 4), // we expire sources; later on will let user change this
      ))
      ->execute();
  }
  else {
    db_update('mediacommons_blocks_blocks')
      ->fields(array(
        'content' => serialize($text),
        'url' => $url,
        'label' => serialize($label),                  
        'proceed' => time(),
        'expire' => time() + (3600 * 4), // we expire sources; later on will let user change this
      ))
      ->condition('mbid', $options['mbid'], '=')
      ->execute();
  }
  // create a wathchdog record
  return mediacommons_blocks_block_load($mbid);
}

function mediacommons_blocks_save_block($options) {
  if (isset($options['type'])) {
    $type = $options['type'];
    $label = (isset($options['label'])) ? check_plain($options['label']) : '';
    $mbid = (isset($options['mbid'])) ? check_plain($options['mbid']) : 'mc_' . time();
    switch ($type) {
      case 'source' :
        return _mediacommons_blocks_save_source($type, $label, $mbid, $options);
        break;
      case 'fulltext' :
        return _mediacommons_blocks_save_fulltext($type, $label, $mbid, $options);
        break;
      case 'plaintext' :
        return _mediacommons_blocks_save_plaintext($type, $label, $mbid, $options);
        break;

      case 'callback' :
        return _mediacommons_blocks_save_callback($type, $label, $mbid, $options);
        break;
    }
  }
}

/**
 * Implements hook_cron().
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_cron/7.x
 */
function mediacommons_blocks_cron () {
  while (TRUE) {
    $update = array(
      'proceed' => time(),
      'expire' => time() + (3600 * 4),
    );
    $item = db_query_range("SELECT mbid, type, url, callback FROM {mediacommons_blocks_blocks} WHERE expire > 0 AND expire > NOW() AND type = '2' ORDER BY proceed ASC", 0, 1, array())->fetchObject();
    if ($item) {
      if ($item->type == 2) { // 2 stands for source. See: mediacommons_blocks_list_types
        if ($item->url) {
          $url = check_url($item->url);
          $request = drupal_http_request($url);
          if ($request->status_message) {
            $status_message = strtolower(check_plain($request->status_message));
            if ($status_message == 'ok') {
              $update['content'] = serialize($request->data);
            }
          }
        }
        $succeeded = db_update('mediacommons_blocks_blocks')->fields($update)->condition('mbid', $item->mbid, '=')->execute();
        if ($succeeded) {
          return $item;
        }
      }
      else { // at the moment we only cache source
        // No items currently available to claim.
        return FALSE;
      }
    }
    else {
      // No items currently available to claim.
      return FALSE;
    }
  }
}

function mediacommons_blocks_blocks () {
  $query = db_query('SELECT * FROM {mediacommons_blocks_blocks}');
  $result = $query->fetchAll();
  $blocks = array();
  foreach ($result as $record) {
    $blocks[] = $record;
  }
  return $blocks;
}

function mediacommons_blocks_block_load ($mbid) {
  $query = db_query('SELECT * FROM {mediacommons_blocks_blocks} WHERE mbid = :mbid', array(':mbid' => $mbid));
  return $query->fetchObject();
}

function mediacommons_blocks_list_types ($label = null) {
  $types = array(
    'plaintext' => 0, // plaint text
    'fulltext' => 1, // HTML
    'source' => 2, // URL
    'callback' => 3, // function to call
  );
  if (isset($types[$label])) {
    return $types[$label];
  } 
  return $types;
}

/**
 * This is here to show how can someone provide a callback as a block
 */
function mediacommons_blocks_callback_example () {
  return '<p>At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint, obcaecati cupiditate non provident, similique sunt in culpa, qui officia deserunt mollitia animi, id est laborum et dolorum fuga.</p>';
}
